# Generated by Django 4.0.6 on 2023-12-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedContent', models.CharField(max_length=100)),
                ('userFeedback', models.CharField(max_length=100)),
            ],
        ),
    ]
